/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Docs - version 1.0
 *
 * The Json to click [this](http://localhost:3000/api-docs/json)
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'App.getHello': ['GET', '/api'],
  'testUser.findAll': ['GET', '/api/user'],
  'testUser.create': ['POST', '/api/user'],
  'testUser.findOne': ['GET', '/api/user/{id}'],
  'testUser.update': ['PATCH', '/api/user/{id}'],
  'testUser.remove': ['DELETE', '/api/user/{id}'],
  'Auth.login': ['POST', '/api/login'],
  'testMenu.findAll': ['GET', '/api/menu'],
  'testMenu.create': ['POST', '/api/menu'],
  'testMenu.findOne': ['GET', '/api/menu/{menuId}'],
  'testMenu.update': ['PATCH', '/api/menu/{menuId}'],
  'testMenu.remove': ['DELETE', '/api/menu/{menuId}'],
  'Product.create': ['POST', '/api/product'],
  'Product.findAll': ['GET', '/api/product'],
  'Product.findOne': ['GET', '/api/product/{productId}'],
  'Product.update': ['PATCH', '/api/product/{productId}'],
  'Product.remove': ['DELETE', '/api/product/{productId}'],
  'Product.getMenuProducts': ['GET', '/api/product/menu/{menuId}']
};
